# Action Requires
# 1. Setup the AZURE_CREDENTIALS secrets in your GitHub Repository
# 2. Setup the REGISTRY_USERNAME secrets in your GitHub Repository
# 3. Setup the REGISTRY_PASSWORD secrets in your GitHub Repository
# 4. Replace REGISTRY, NAMESPACE, IMAGE, TAG in the following template with proper values
# 5. Add this yaml file to your project's .github/workflows/
# 6. Push your local project to your GitHub Repository
#change

name: MokdimAI_Linux_Container_Workflow

env:
  REPO: digitalidf/mokdimai/meitavstt-functionapp-pp
  APP_NAME: MokdimAI-Preprod


on:
  push:
    branches:
      - FunctionApp_Grid

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: "Preprod"
      url: ${{ steps.deploy-to-functionapp.outputs.webapp-url }}

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}:latest 
          file: ./Dockerfile

  deploy:
    runs-on: [self-hosted, azure]
    needs: build
    environment: 
      name: "Preprod"
      url: ${{ steps.deploy-to-functionapp.outputs.webapp-url }}

    steps:
      - name: Lowercase the repo name and username
        id: string
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Deploy to Azure Function App
        id: deploy-to-functionapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PP_PUBLISH_PROFILE }}
          images: "ghcr.io/${{ env.REPO }}"
    
# For more information on GitHub Actions:
#   https://help.github.com/en/categories/automating-your-workflow-with-github-actions
